# Generated by Django 2.2.2 on 2019-08-20 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaveapply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('l_type', models.CharField(max_length=100)),
                ('l_days', models.CharField(max_length=100)),
                ('l_from', models.DateField(default=django.utils.timezone.now, max_length=30)),
                ('l_to', models.DateField(default=django.utils.timezone.now, max_length=30)),
                ('l_status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'leaveapply',
            },
        ),
        migrations.CreateModel(
            name='Leavemngt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='0', max_length=50)),
                ('uname', models.CharField(default='0', max_length=50)),
                ('pwd', models.CharField(default='0', max_length=20)),
                ('cpwd', models.CharField(default='0', max_length=20)),
            ],
            options={
                'db_table': 'leavemngt',
            },
        ),
    ]
